version: '3.8'

services:
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  postgres:
    image: postgres:latest
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=wallettest
      - POSTGRES_DB=root
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "cleitonj198905@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "80:80"  
    depends_on:
      - postgres

  events:
    build:
      context: ./events
      dockerfile: Dockerfile
    ports: 
      - "8081:8081"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - kafka
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092

  wallets:
    build:
      context: ./wallet
      dockerfile: Dockerfile
    ports: 
      - "8089:8089"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - kafka
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092