basePath: /
definitions:
  requestdto.EventRequest:
    properties:
      description:
        type: string
      event_uuid:
        type: string
      id:
        type: integer
      id_uuid:
        type: string
      type_id:
        type: integer
      value:
        type: number
      wallet_uuid:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8081
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /api/v1/event:
    post:
      consumes:
      - application/json
      description: Post create event
      parameters:
      - description: Event Identification
        in: body
        name: event
        required: true
        schema:
          $ref: '#/definitions/requestdto.EventRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema:
            type: Bad
      summary: Post create event
      tags:
      - event
swagger: "2.0"
